<a href="https://colab.research.google.com/github/trong-shen/Game-of-Throne-Project/blob/master/S1%2BS2subtitles.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Season 1 Episode 1

In [0]:
import pandas as pd
import datetime as dt
import numpy as np
import re

GOTep1_2=pd.read_csv('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/subtitlesEp1.csv',delimiter=";")

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/subtitlesEp1.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]      
print(lines)

In [0]:
GOTep1=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep1.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep1['Time_End'] = pd.to_datetime(GOTep1['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep1['Time_Start'] = pd.to_datetime(GOTep1['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep1['Time_End'] = pd.to_timedelta(GOTep1['Time_End'].astype(str))
GOTep1['Time_Start'] = pd.to_timedelta(GOTep1['Time_Start'].astype(str))

In [133]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep1['Time_Diff_seconds'] = GOTep1['Time_End'] - GOTep1['Time_Start']
GOTep1['Time_Diff_seconds'] = GOTep1['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep1.tail(5)

         Time_Start  ... Time_Diff_seconds
661 01:00:03.178000  ...             1.701
662 01:00:06.081000  ...             2.435
663 01:00:09.652000  ...             2.935
664 01:00:12.621000  ...             1.700
665 01:00:23.030000  ...             2.502

[5 rows x 4 columns]

In [0]:
GOTep1.drop(index=666, inplace=True)

# episode 2

In [8]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

['00:01:38,619', '00:01:42,620', '00:02:10,767', '00:02:16,684', '00:02:22,489', '00:02:26,026', '00:02:28,562', '00:02:41,342', '00:02:44,044', '00:02:46,480', '00:02:49,616', '00:02:52,286', '00:02:54,822', '00:03:10,871', '00:03:51,178', '00:03:52,679', '00:04:05,192', '00:04:07,895', '00:04:10,397', '00:04:12,433', '00:04:14,868', '00:04:17,371', '00:04:19,740', '00:04:23,243', '00:04:25,345', '00:04:29,283', '00:04:31,552', '00:04:33,587', '00:04:36,423', '00:04:40,461', '00:04:43,630', '00:05:10,724', '00:05:17,498', '00:05:20,134', '00:05:22,536', '00:05:25,672', '00:05:27,774', '00:05:32,412', '00:05:35,282', '00:05:37,417', '00:05:39,586', '00:05:44,191', '00:05:46,126', '00:05:48,762', '00:05:51,398', '00:05:53,534', '00:05:55,569', '00:05:58,438', '00:06:01,942', '00:06:04,144', '00:06:12,519', '00:06:14,721', '00:06:16,757', '00:06:22,996', '00:06:33,173', '00:06:36,376', '00:06:42,349', '00:06:44,451', '00:06:46,453', '00:06:53,827', '00:06:57,631', '00:07:01,902', '00:07:13,580', '00:07:16,683', '00:07:18,485', '00:07:22,456', '00:07:25,058', '00:07:27,027', '00:07:29,062', '00:07:30,831', '00:07:35,102', '00:07:37,671', '00:07:40,641', '00:07:43,577', '00:07:45,712', '00:07:47,714', '00:07:51,218', '00:07:55,722', '00:08:03,664', '00:08:07,078', '00:08:11,471', '00:08:14,808', '00:08:18,045', '00:08:21,448', '00:08:22,983', '00:08:28,088', '00:08:29,990', '00:08:32,693', '00:08:35,062', '00:08:56,850', '00:08:58,118', '00:09:01,555', '00:09:07,194', '00:09:09,262', '00:09:14,101', '00:09:17,237', '00:09:20,640', '00:09:22,909', '00:09:24,945', '00:09:27,214', '00:09:30,617', '00:09:33,653', '00:09:42,362', '00:09:46,233', '00:09:49,002', '00:09:54,007', '00:09:58,845', '00:10:06,219', '00:10:10,023', '00:10:12,526', '00:10:25,472', '00:10:27,541', '00:10:31,745', '00:10:33,480', '00:11:27,601', '00:11:31,771', '00:11:34,407', '00:11:37,644', '00:11:43,850', '00:11:46,987', '00:11:50,190', '00:11:55,829', '00:11:58,031', '00:12:00,901', '00:12:05,639', '00:12:07,307', '00:12:12,212', '00:12:17,651', '00:12:21,721', '00:12:23,423', '00:12:26,993', '00:12:29,296', '00:12:32,766', '00:12:34,734', '00:12:56,289', '00:13:05,065', '00:13:08,068', '00:13:10,737', '00:13:12,477', '00:13:15,109', '00:13:16,276', '00:13:18,144', '00:13:26,152', '00:13:28,188', '00:13:32,125', '00:13:34,694', '00:13:37,063', '00:13:38,898', '00:13:53,380', '00:13:58,485', '00:14:04,090', '00:14:07,494', '00:14:09,396', '00:14:10,897', '00:14:13,066', '00:14:14,128', '00:14:17,003', '00:14:18,471', '00:14:21,174', '00:14:24,711', '00:14:27,213', '00:14:34,721', '00:14:38,358', '00:14:51,004', '00:14:56,676', '00:15:00,780', '00:15:17,630', '00:15:19,766', '00:15:32,212', '00:15:38,218', '00:15:40,787', '00:15:51,464', '00:15:54,234', '00:15:59,939', '00:16:02,308', '00:16:10,150', '00:16:27,801', '00:16:30,103', '00:17:32,031', '00:17:34,234', '00:17:38,605', '00:17:43,409', '00:17:48,781', '00:17:50,583', '00:17:54,487', '00:17:59,626', '00:18:01,995', '00:18:07,901', '00:18:15,608', '00:18:21,281', '00:18:26,786', '00:18:52,011', '00:18:54,580', '00:18:57,050', '00:19:00,253', '00:19:01,988', '00:19:06,192', '00:19:08,494', '00:19:11,864', '00:20:07,453', '00:20:12,025', '00:20:15,495', '00:20:18,498', '00:20:20,800', '00:20:29,242', '00:20:31,677', '00:20:36,482', '00:20:39,752', '00:20:42,088', '00:20:44,457', '00:20:46,359', '00:21:28,034', '00:21:32,805', '00:21:38,511', '00:21:40,847', '00:21:42,915', '00:21:45,485', '00:21:49,088', '00:21:51,791', '00:21:54,694', '00:21:56,796', '00:22:02,668', '00:22:05,371', '00:22:07,373', '00:22:10,243', '00:22:12,578', '00:22:16,249', '00:22:19,118', '00:22:21,554', '00:22:24,657', '00:22:28,327', '00:22:30,630', '00:22:32,832', '00:22:35,701', '00:22:37,970', '00:22:42,808', '00:22:44,710', '00:22:47,413', '00:22:52,785', '00:22:56,022', '00:22:59,125', '00:23:03,829', '00:23:10,369', '00:23:18,477', '00:23:22,014', '00:23:24,717', '00:23:26,452', '00:23:28,454', '00:23:30,423', '00:23:33,693', '00:23:37,396', '00:23:41,300', '00:23:43,402', '00:23:45,571', '00:23:48,874', '00:23:51,110', '00:23:53,079', '00:23:55,448', '00:23:58,251', '00:24:01,087', '00:24:03,089', '00:24:07,793', '00:24:11,097', '00:24:15,601', '00:24:23,542', '00:24:25,678', '00:24:27,546', '00:24:30,116', '00:25:43,356', '00:25:45,291', '00:25:50,596', '00:25:52,998', '00:25:58,504', '00:26:02,375', '00:26:09,415', '00:26:15,020', '00:26:16,989', '00:26:29,168', '00:26:31,370', '00:26:35,808', '00:26:37,743', '00:26:41,480', '00:26:44,950', '00:26:48,788', '00:26:51,357', '00:26:53,826', '00:27:01,534', '00:27:07,406', '00:27:11,243', '00:27:13,245', '00:27:19,051', '00:27:24,056', '00:27:26,025', '00:27:28,861', '00:27:30,796', '00:27:34,133', '00:27:40,573', '00:27:43,075', '00:27:47,613', '00:27:54,386', '00:27:57,389', '00:27:59,358', '00:28:01,861', '00:28:05,865', '00:28:07,967', '00:28:11,237', '00:28:14,707', '00:28:17,109', '00:28:27,052', '00:29:04,590', '00:29:08,527', '00:29:14,199', '00:29:18,137', '00:29:21,273', '00:29:24,009', '00:29:27,212', '00:29:32,618', '00:29:37,222', '00:29:39,162', '00:29:43,596', '00:29:58,110', '00:30:00,346', '00:30:03,015', '00:30:04,883', '00:30:07,095', '00:30:08,557', '00:30:12,324', '00:30:14,293', '00:30:17,730', '00:30:20,199', '00:30:26,071', '00:30:28,607', '00:30:48,494', '00:30:51,030', '00:30:53,799', '00:31:00,039', '00:32:08,474', '00:32:12,277', '00:32:15,347', '00:32:18,317', '00:32:21,553', '00:32:25,624', '00:32:28,026', '00:32:30,229', '00:32:33,298', '00:32:37,169', '00:32:40,439', '00:32:42,407', '00:32:45,344', '00:32:48,213', '00:32:52,518', '00:33:02,327', '00:33:05,631', '00:33:08,867', '00:33:10,936', '00:33:13,071', '00:33:16,275', '00:33:18,310', '00:33:19,845', '00:33:23,315', '00:33:24,883', '00:33:29,688', '00:33:34,393', '00:33:39,698', '00:34:02,821', '00:35:35,414', '00:35:40,485', '00:35:44,323', '00:35:47,659', '00:35:50,462', '00:35:53,231', '00:35:56,368', '00:35:59,137', '00:36:03,408', '00:36:05,677', '00:36:09,147', '00:36:11,483', '00:36:13,952', '00:36:17,289', '00:36:20,592', '00:36:24,162', '00:36:26,408', '00:36:28,100', '00:36:31,003', '00:36:33,005', '00:36:36,008', '00:36:38,110', '00:36:40,679', '00:36:43,648', '00:36:45,584', '00:36:48,920', '00:36:51,289', '00:36:53,458', '00:36:56,194', '00:36:58,730', '00:37:01,066', '00:37:02,934', '00:37:09,574', '00:37:13,445', '00:37:17,716', '00:38:19,778', '00:38:22,080', '00:38:24,916', '00:38:26,985', '00:38:31,456', '00:38:33,525', '00:38:37,329', '00:38:39,464', '00:38:44,035', '00:38:46,705', '00:38:50,475', '00:38:54,279', '00:38:57,149', '00:39:00,752', '00:39:02,721', '00:39:05,023', '00:39:07,559', '00:39:09,828', '00:39:13,064', '00:39:27,145', '00:39:38,390', '00:39:40,792', '00:39:42,994', '00:39:47,098', '00:39:49,367', '00:39:51,469', '00:39:54,072', '00:40:45,523', '00:40:50,795', '00:40:52,731', '00:42:43,842', '00:42:49,514', '00:42:53,551', '00:42:56,354', '00:42:58,990', '00:43:01,493', '00:43:10,869', '00:43:12,838', '00:43:15,039', '00:43:18,143', '00:43:20,912', '00:43:26,184', '00:43:29,621', '00:43:34,359', '00:43:36,461', '00:43:38,196', '00:43:43,067', '00:43:47,705', '00:43:49,541', '00:43:53,244', '00:44:12,030', '00:44:14,265', '00:44:16,668', '00:44:32,150', '00:44:35,920', '00:44:43,194', '00:44:46,164', '00:44:47,765', '00:44:53,972', '00:44:56,808', '00:44:58,943', '00:45:04,015', '00:45:06,885', '00:45:09,521', '00:45:11,523', '00:45:13,491', '00:45:17,161', '00:45:19,531', '00:45:22,734', '00:45:25,003', '00:45:28,072', '00:45:31,342', '00:45:33,144', '00:45:43,254', '00:45:45,523', '00:45:46,958', '00:45:48,893', '00:45:52,263', '00:45:57,602', '00:45:59,737', '00:46:07,178', '00:46:09,147', '00:46:11,783', '00:46:32,804', '00:46:36,307', '00:46:38,776', '00:46:41,913', '00:46:46,351', '00:46:55,326', '00:46:59,330', '00:47:04,569', '00:47:08,840', '00:47:16,881', '00:47:22,053', '00:47:35,667', '00:47:38,836', '00:47:43,574', '00:47:47,612', '00:47:49,714', '00:47:51,482', '00:47:53,451', '00:47:55,887', '00:47:58,389', '00:47:59,932', '00:48:01,713', '00:48:03,823', '00:48:06,061', '00:48:08,662', '00:48:11,102', '00:48:20,611', '00:48:22,513', '00:48:24,282', '00:48:28,519', '00:48:31,322', '00:48:34,415', '00:48:36,080', '00:48:38,229', '00:48:41,165', '00:48:43,501', '00:48:47,105', '00:48:49,774', '00:48:51,743', '00:48:54,245', '00:48:57,882', '00:48:59,817', '00:49:02,720', '00:49:04,371', '00:49:06,124', '00:49:07,425', '00:49:08,860', '00:49:11,929', '00:49:16,367', '00:49:18,450', '00:49:20,265', '00:49:22,458', '00:49:34,752', '00:49:37,655', '00:49:39,757', '00:49:41,859', '00:49:52,904', '00:49:54,872', '00:49:59,210', '00:50:01,712', '00:50:03,214', '00:50:05,550', '00:50:09,988', '00:50:11,010', '00:50:14,264', '00:50:17,002', '00:50:21,273', '00:50:30,916', '00:50:34,086', '00:50:38,190', '00:50:40,860', '00:50:46,332', '00:50:48,868', '00:50:51,670', '00:50:54,974', '00:51:00,446', '00:51:02,114', '00:51:05,351', '00:51:08,921', '00:51:11,323', '00:51:14,360', '00:51:16,295', '00:51:19,732', '00:51:22,501', '00:51:25,070', '00:51:33,012', '00:51:36,582', '00:51:38,784', '00:51:41,120', '00:51:44,590', '00:51:50,830', '00:51:53,465', '00:51:55,467', '00:51:57,703', '00:52:00,673', '00:52:37,142', '00:52:39,144', '00:52:40,846', '00:52:43,015', '00:54:15,231']
['00:01:42,619', '00:01:46,120', '00:02:13,034', '00:02:18,885', '00:02:24,857', '00:02:28,528', '00:02:32,332', '00:02:44,010', '00:02:46,412', '00:02:49,582', '00:02:52,251', '00:02:54,754', '00:02:58,024', '00:03:13,072', '00:03:51,210', '00:03:54,647', '00:04:07,827', '00:04:10,329', '00:04:12,398', '00:04:14,834', '00:04:17,336', '00:04:19,672', '00:04:22,075', '00:04:25,311', '00:04:27,747', '00:04:31,517', '00:04:33,519', '00:04:36,355', '00:04:38,858', '00:04:43,596', '00:04:45,965', '00:05:13,559', '00:05:20,099', '00:05:22,502', '00:05:25,638', '00:05:27,740', '00:05:30,710', '00:05:35,248', '00:05:37,383', '00:05:39,552', '00:05:42,021', '00:05:46,092', '00:05:47,894', '00:05:51,364', '00:05:53,499', '00:05:55,535', '00:05:58,404', '00:06:01,908', '00:06:04,110', '00:06:05,711', '00:06:14,687', '00:06:16,722', '00:06:20,259', '00:06:26,132', '00:06:36,309', '00:06:39,779', '00:06:44,417', '00:06:46,419', '00:06:49,455', '00:06:55,828', '00:06:59,732', '00:07:05,504', '00:07:16,649', '00:07:18,451', '00:07:21,020', '00:07:25,024', '00:07:26,993', '00:07:29,028', '00:07:30,796', '00:07:35,034', '00:07:37,637', '00:07:40,606', '00:07:43,542', '00:07:45,678', '00:07:47,680', '00:07:49,815', '00:07:53,886', '00:07:57,556', '00:08:07,077', '00:08:10,264', '00:08:14,740', '00:08:18,010', '00:08:20,046', '00:08:22,948', '00:08:25,584', '00:08:29,955', '00:08:32,658', '00:08:35,027', '00:08:37,630', '00:08:58,084', '00:09:01,520', '00:09:04,023', '00:09:09,228', '00:09:14,066', '00:09:17,203', '00:09:20,573', '00:09:22,875', '00:09:24,910', '00:09:27,179', '00:09:29,048', '00:09:33,586', '00:09:37,490', '00:09:44,563', '00:09:48,934', '00:09:51,837', '00:09:58,844', '00:10:00,978', '00:10:08,220', '00:10:12,491', '00:10:14,860', '00:10:27,506', '00:10:29,775', '00:10:33,446', '00:10:36,549', '00:11:29,635', '00:11:34,373', '00:11:37,610', '00:11:39,278', '00:11:46,952', '00:11:50,155', '00:11:53,626', '00:11:57,997', '00:12:00,866', '00:12:03,502', '00:12:07,273', '00:12:09,675', '00:12:14,980', '00:12:20,185', '00:12:23,389', '00:12:24,690', '00:12:29,261', '00:12:32,731', '00:12:34,700', '00:12:37,603', '00:12:58,357', '00:13:08,033', '00:13:10,703', '00:13:12,476', '00:13:13,902', '00:13:16,275', '00:13:18,110', '00:13:20,045', '00:13:28,153', '00:13:30,789', '00:13:34,660', '00:13:37,029', '00:13:38,864', '00:13:41,000', '00:13:55,848', '00:14:01,353', '00:14:06,258', '00:14:09,361', '00:14:10,863', '00:14:13,032', '00:14:14,103', '00:14:15,824', '00:14:18,437', '00:14:21,140', '00:14:23,342', '00:14:27,179', '00:14:29,248', '00:14:36,789', '00:14:39,792', '00:14:53,939', '00:14:59,311', '00:15:02,915', '00:15:19,732', '00:15:21,500', '00:15:35,247', '00:15:40,753', '00:15:42,554', '00:15:54,199', '00:15:58,103', '00:16:02,274', '00:16:05,077', '00:16:13,185', '00:16:30,035', '00:16:31,703', '00:17:34,199', '00:17:36,401', '00:17:41,940', '00:17:46,111', '00:17:50,549', '00:17:54,453', '00:17:58,056', '00:18:01,960', '00:18:04,763', '00:18:09,935', '00:18:18,310', '00:18:24,483', '00:18:28,587', '00:18:54,546', '00:18:57,015', '00:18:59,351', '00:19:01,954', '00:19:04,456', '00:19:08,460', '00:19:10,662', '00:19:15,000', '00:20:09,988', '00:20:15,460', '00:20:18,463', '00:20:20,732', '00:20:22,901', '00:20:31,643', '00:20:34,880', '00:20:38,583', '00:20:42,054', '00:20:44,423', '00:20:46,324', '00:20:48,427', '00:21:31,036', '00:21:36,374', '00:21:40,812', '00:21:42,881', '00:21:45,450', '00:21:49,054', '00:21:51,756', '00:21:54,659', '00:21:56,761', '00:21:58,797', '00:22:05,337', '00:22:07,339', '00:22:10,175', '00:22:12,544', '00:22:16,214', '00:22:19,084', '00:22:21,520', '00:22:24,623', '00:22:26,691', '00:22:30,595', '00:22:32,797', '00:22:35,667', '00:22:37,936', '00:22:40,338', '00:22:44,676', '00:22:47,379', '00:22:50,882', '00:22:55,987', '00:22:59,057', '00:23:01,660', '00:23:06,398', '00:23:12,404', '00:23:21,980', '00:23:24,683', '00:23:26,418', '00:23:28,386', '00:23:30,388', '00:23:33,658', '00:23:37,362', '00:23:41,266', '00:23:43,368', '00:23:45,537', '00:23:48,840', '00:23:51,076', '00:23:53,044', '00:23:55,413', '00:23:58,216', '00:24:01,052', '00:24:03,054', '00:24:06,258', '00:24:11,062', '00:24:13,898', '00:24:18,770', '00:24:25,644', '00:24:27,512', '00:24:30,081', '00:24:31,616', '00:25:45,256', '00:25:47,292', '00:25:52,964', '00:25:56,468', '00:26:02,307', '00:26:04,776', '00:26:12,317', '00:26:16,955', '00:26:20,492', '00:26:31,336', '00:26:34,639', '00:26:37,675', '00:26:41,446', '00:26:44,916', '00:26:48,753', '00:26:51,322', '00:26:53,792', '00:26:56,027', '00:27:05,503', '00:27:10,041', '00:27:13,211', '00:27:16,448', '00:27:22,353', '00:27:25,990', '00:27:28,827', '00:27:30,728', '00:27:34,098', '00:27:37,235', '00:27:43,041', '00:27:45,410', '00:27:50,615', '00:27:57,355', '00:27:59,324', '00:28:01,826', '00:28:05,830', '00:28:07,932', '00:28:11,202', '00:28:14,672', '00:28:17,075', '00:28:19,711', '00:28:30,188', '00:29:08,459', '00:29:12,630', '00:29:16,801', '00:29:21,239', '00:29:23,975', '00:29:27,178', '00:29:31,316', '00:29:34,485', '00:29:39,137', '00:29:41,362', '00:29:45,229', '00:30:00,311', '00:30:02,981', '00:30:04,882', '00:30:07,094', '00:30:08,461', '00:30:12,261', '00:30:14,258', '00:30:17,695', '00:30:20,164', '00:30:22,367', '00:30:28,573', '00:30:30,775', '00:30:50,995', '00:30:53,731', '00:30:57,368', '00:31:02,740', '00:32:12,243', '00:32:15,313', '00:32:18,282', '00:32:21,519', '00:32:25,590', '00:32:27,959', '00:32:30,194', '00:32:33,264', '00:32:37,135', '00:32:40,404', '00:32:42,373', '00:32:45,309', '00:32:48,179', '00:32:50,982', '00:32:54,485', '00:33:05,596', '00:33:08,833', '00:33:10,902', '00:33:13,004', '00:33:16,240', '00:33:18,276', '00:33:19,811', '00:33:23,281', '00:33:24,849', '00:33:26,851', '00:33:33,191', '00:33:38,296', '00:33:41,365', '00:34:05,022', '00:35:38,983', '00:35:43,120', '00:35:46,324', '00:35:50,428', '00:35:53,197', '00:35:56,334', '00:35:59,103', '00:36:01,839', '00:36:05,643', '00:36:09,113', '00:36:11,449', '00:36:13,918', '00:36:17,254', '00:36:19,190', '00:36:24,128', '00:36:26,383', '00:36:28,096', '00:36:30,968', '00:36:32,970', '00:36:35,973', '00:36:38,042', '00:36:40,644', '00:36:43,614', '00:36:45,549', '00:36:48,886', '00:36:51,222', '00:36:53,424', '00:36:56,160', '00:36:58,696', '00:37:01,032', '00:37:02,900', '00:37:05,836', '00:37:11,909', '00:37:16,547', '00:37:21,085', '00:38:22,046', '00:38:24,882', '00:38:26,951', '00:38:31,422', '00:38:33,491', '00:38:35,826', '00:38:39,430', '00:38:44,001', '00:38:46,670', '00:38:50,441', '00:38:54,245', '00:38:57,114', '00:39:00,718', '00:39:02,686', '00:39:04,989', '00:39:07,525', '00:39:09,793', '00:39:13,030', '00:39:16,534', '00:39:30,014', '00:39:40,758', '00:39:42,960', '00:39:47,064', '00:39:49,333', '00:39:51,435', '00:39:54,038', '00:39:57,074', '00:40:48,392', '00:40:52,696', '00:40:57,401', '00:42:45,676', '00:42:51,849', '00:42:56,320', '00:42:58,956', '00:43:01,458', '00:43:04,261', '00:43:12,837', '00:43:15,038', '00:43:18,108', '00:43:20,878', '00:43:24,681', '00:43:28,318', '00:43:32,790', '00:43:36,427', '00:43:38,162', '00:43:40,864', '00:43:45,202', '00:43:49,506', '00:43:51,308', '00:43:55,379', '00:44:14,231', '00:44:16,633', '00:44:19,736', '00:44:34,918', '00:44:38,021', '00:44:46,129', '00:44:47,731', '00:44:50,234', '00:44:56,773', '00:44:58,909', '00:45:02,412', '00:45:06,850', '00:45:09,486', '00:45:11,488', '00:45:13,457', '00:45:17,094', '00:45:19,496', '00:45:21,398', '00:45:24,968', '00:45:28,038', '00:45:30,407', '00:45:33,110', '00:45:34,745', '00:45:44,521', '00:45:46,924', '00:45:48,859', '00:45:52,229', '00:45:54,898', '00:45:59,703', '00:46:02,306', '00:46:09,112', '00:46:11,748', '00:46:14,217', '00:46:36,273', '00:46:38,742', '00:46:40,110', '00:46:44,348', '00:46:49,319', '00:46:59,296', '00:47:01,465', '00:47:06,737', '00:47:11,308', '00:47:20,484', '00:47:23,687', '00:47:38,802', '00:47:43,540', '00:47:46,476', '00:47:49,680', '00:47:51,448', '00:47:53,417', '00:47:55,852', '00:47:58,355', '00:47:59,907', '00:48:01,658', '00:48:03,547', '00:48:05,991', '00:48:08,441', '00:48:10,897', '00:48:12,969', '00:48:22,479', '00:48:24,247', '00:48:26,817', '00:48:31,254', '00:48:34,041', '00:48:36,055', '00:48:37,280', '00:48:41,131', '00:48:43,433', '00:48:47,070', '00:48:49,740', '00:48:51,708', '00:48:54,211', '00:48:57,848', '00:48:59,783', '00:49:02,686', '00:49:04,346', '00:49:06,121', '00:49:07,390', '00:49:08,825', '00:49:11,895', '00:49:14,297', '00:49:18,425', '00:49:19,802', '00:49:21,566', '00:49:24,793', '00:49:36,753', '00:49:39,723', '00:49:41,825', '00:49:44,494', '00:49:54,838', '00:49:58,308', '00:50:01,678', '00:50:03,180', '00:50:05,515', '00:50:09,911', '00:50:11,009', '00:50:13,742', '00:50:16,966', '00:50:19,604', '00:50:24,909', '00:50:34,052', '00:50:36,955', '00:50:40,825', '00:50:43,461', '00:50:48,833', '00:50:51,636', '00:50:54,939', '00:50:57,142', '00:51:02,080', '00:51:05,316', '00:51:07,786', '00:51:11,289', '00:51:14,325', '00:51:16,261', '00:51:19,664', '00:51:22,467', '00:51:24,002', '00:51:26,604', '00:51:36,548', '00:51:38,750', '00:51:41,085', '00:51:43,488', '00:51:46,624', '00:51:53,431', '00:51:55,433', '00:51:57,669', '00:52:00,638', '00:52:03,775', '00:52:39,077', '00:52:40,812', '00:52:42,981', '00:52:44,716', '00:54:19,231']

In [9]:
GOTep2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time_Start  583 non-null    object
 1   Time_End    583 non-null    object
 2   Text        583 non-null    object
dtypes: object(3)
memory usage: 13.8+ KB

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep2['Time_End'] = pd.to_datetime(GOTep2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep2['Time_Start'] = pd.to_datetime(GOTep2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep2['Time_End'] = pd.to_timedelta(GOTep2['Time_End'].astype(str))
GOTep2['Time_Start'] = pd.to_timedelta(GOTep2['Time_Start'].astype(str))

In [136]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep2['Time_Diff_seconds'] = GOTep2['Time_End'] - GOTep2['Time_Start']
GOTep2['Time_Diff_seconds'] = GOTep2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep2.tail(5)

         Time_Start  ... Time_Diff_seconds
577 00:52:00.673000  ...             3.102
578 00:52:37.142000  ...             1.935
579 00:52:39.144000  ...             1.668
580 00:52:40.846000  ...             2.135
581 00:52:43.015000  ...             1.701

[5 rows x 4 columns]

In [0]:
GOTep2.drop(index=582, inplace=True)

# episode 3

In [13]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp3.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

['00:02:13,537', '00:02:14,973', '00:02:18,308', '00:02:21,910', '00:02:25,047', '00:02:27,717', '00:03:07,624', '00:03:10,927', '00:03:15,365', '00:03:17,100', '00:03:19,169', '00:03:21,672', '00:03:23,707', '00:03:26,844', '00:03:30,348', '00:03:32,784', '00:03:36,355', '00:03:40,460', '00:03:45,632', '00:03:51,037', '00:03:55,008', '00:03:57,110', '00:03:58,945', '00:04:01,114', '00:04:04,017', '00:04:05,919', '00:04:08,922', '00:04:11,725', '00:04:14,161', '00:04:16,797', '00:04:23,069', '00:04:25,572', '00:04:28,442', '00:04:31,211', '00:04:33,879', '00:04:38,551', '00:04:43,222', '00:04:46,959', '00:04:49,729', '00:04:51,832', '00:04:54,435', '00:04:56,238', '00:04:59,308', '00:05:01,911', '00:05:04,480', '00:05:19,263', '00:05:23,934', '00:05:25,770', '00:05:29,173', '00:05:32,843', '00:05:37,413', '00:05:40,749', '00:05:42,551', '00:05:44,753', '00:05:47,556', '00:05:50,859', '00:05:54,496', '00:05:57,599', '00:06:00,869', '00:06:02,872', '00:06:04,974', '00:06:06,976', '00:06:09,380', '00:06:12,750', '00:06:15,453', '00:06:18,123', '00:06:20,360', '00:06:25,832', '00:06:30,170', '00:06:35,108', '00:06:38,044', '00:06:39,946', '00:06:43,283', '00:06:45,385', '00:06:48,420', '00:06:50,256', '00:06:58,129', '00:07:00,632', '00:07:03,501', '00:07:07,205', '00:07:08,941', '00:07:12,111', '00:07:14,448', '00:07:17,417', '00:07:20,387', '00:07:22,556', '00:07:24,657', '00:07:26,592', '00:07:28,394', '00:07:30,863', '00:07:32,631', '00:07:34,466', '00:07:37,469', '00:07:39,771', '00:07:43,708', '00:07:46,111', '00:07:49,013', '00:07:51,415', '00:07:53,583', '00:07:59,455', '00:08:01,490', '00:08:05,195', '00:08:15,407', '00:08:20,312', '00:08:23,749', '00:08:27,586', '00:08:29,922', '00:08:31,958', '00:08:34,260', '00:08:37,364', '00:08:40,600', '00:08:41,547', '00:08:43,737', '00:08:46,239', '00:08:54,212', '00:08:56,114', '00:08:59,216', '00:09:01,351', '00:09:04,622', '00:09:10,161', '00:09:13,731', '00:09:16,867', '00:09:18,936', '00:09:24,342', '00:09:26,677', '00:09:28,980', '00:09:34,186', '00:09:36,155', '00:09:38,557', '00:09:40,726', '00:09:42,928', '00:09:46,464', '00:09:49,767', '00:09:52,136', '00:09:55,105', '00:09:56,974', '00:10:00,610', '00:10:03,212', '00:10:04,881', '00:10:07,617', '00:10:10,587', '00:10:14,290', '00:10:16,759', '00:10:18,894', '00:10:21,697', '00:10:24,733', '00:10:27,402', '00:10:30,772', '00:10:35,243', '00:10:37,611', '00:10:40,380', '00:10:44,785', '00:10:47,555', '00:10:51,826', '00:10:54,463', '00:10:56,399', '00:10:58,501', '00:11:01,704', '00:11:03,617', '00:11:05,675', '00:11:08,311', '00:11:12,615', '00:11:14,350', '00:11:19,321', '00:11:29,500', '00:11:40,779', '00:11:46,451', '00:11:48,587', '00:11:52,926', '00:11:56,864', '00:12:08,575', '00:12:15,113', '00:12:17,749', '00:12:30,260', '00:12:38,968', '00:12:41,738', '00:12:50,247', '00:12:55,287', '00:13:01,027', '00:13:05,130', '00:13:08,099', '00:13:10,067', '00:13:17,708', '00:13:20,076', '00:13:22,011', '00:13:25,882', '00:13:28,618', '00:13:30,387', '00:13:32,789', '00:13:34,591', '00:13:40,230', '00:13:44,201', '00:13:48,740', '00:13:51,744', '00:13:54,480', '00:13:59,185', '00:14:02,455', '00:14:05,091', '00:14:06,718', '00:14:10,364', '00:14:13,033', '00:14:15,569', '00:14:19,139', '00:14:22,209', '00:14:24,545', '00:14:28,650', '00:14:33,222', '00:14:36,726', '00:14:39,262', '00:14:44,667', '00:14:47,402', '00:14:49,838', '00:14:51,973', '00:14:54,042', '00:14:56,977', '00:15:02,649', '00:15:05,052', '00:15:08,488', '00:15:10,491', '00:15:12,359', '00:15:14,795', '00:15:19,334', '00:15:21,369', '00:15:27,809', '00:15:29,743', '00:15:41,486', '00:15:43,889', '00:15:53,563', '00:15:59,435', '00:16:03,072', '00:16:06,943', '00:16:10,347', '00:16:12,350', '00:16:14,752', '00:16:18,791', '00:16:24,463', '00:16:26,299', '00:16:29,302', '00:16:31,438', '00:16:34,441', '00:16:37,212', '00:16:39,948', '00:16:43,018', '00:16:47,722', '00:16:50,926', '00:16:53,061', '00:16:56,031', '00:16:58,300', '00:17:01,203', '00:17:03,372', '00:17:07,410', '00:17:14,151', '00:17:16,287', '00:17:18,823', '00:17:21,993', '00:17:24,194', '00:17:32,348', '00:17:34,815', '00:17:36,939', '00:17:50,185', '00:17:52,621', '00:17:54,924', '00:17:57,794', '00:18:02,364', '00:18:08,069', '00:18:12,140', '00:18:14,175', '00:18:16,377', '00:18:18,279', '00:18:20,413', '00:18:25,752', '00:18:28,054', '00:18:38,865', '00:18:42,202', '00:18:57,053', '00:18:59,723', '00:19:01,758', '00:19:04,427', '00:19:11,333', '00:19:13,869', '00:19:17,172', '00:19:19,073', '00:19:21,409', '00:19:23,244', '00:19:25,980', '00:19:38,627', '00:19:41,464', '00:19:45,502', '00:19:48,238', '00:19:51,041', '00:19:54,378', '00:19:58,014', '00:20:00,083', '00:20:02,485', '00:20:04,654', '00:20:06,489', '00:20:09,158', '00:20:12,728', '00:20:16,299', '00:20:19,935', '00:20:22,805', '00:20:26,842', '00:20:30,778', '00:20:32,413', '00:20:36,683', '00:20:40,820', '00:20:43,255', '00:20:45,524', '00:20:54,466', '00:20:56,568', '00:21:00,539', '00:21:02,808', '00:21:06,712', '00:21:08,847', '00:21:13,284', '00:21:18,590', '00:21:21,192', '00:21:25,797', '00:21:28,666', '00:21:30,502', '00:21:33,038', '00:21:35,641', '00:21:37,843', '00:21:39,746', '00:21:41,948', '00:21:50,123', '00:21:53,126', '00:21:56,429', '00:21:58,764', '00:22:00,900', '00:22:02,936', '00:22:12,245', '00:22:24,526', '00:22:39,739', '00:22:41,474', '00:22:45,177', '00:22:46,645', '00:22:49,582', '00:22:52,585', '00:22:54,720', '00:22:57,424', '00:22:59,292', '00:23:02,129', '00:23:06,767', '00:23:08,436', '00:23:13,909', '00:23:16,445', '00:23:19,415', '00:23:22,618', '00:23:27,756', '00:23:31,793', '00:23:45,272', '00:23:50,911', '00:23:56,050', '00:24:06,661', '00:24:12,233', '00:24:14,269', '00:24:19,407', '00:24:20,909', '00:24:24,780', '00:24:33,690', '00:24:35,526', '00:24:43,535', '00:24:53,478', '00:24:58,716', '00:25:01,919', '00:25:08,660', '00:25:10,795', '00:25:13,364', '00:25:15,667', '00:25:19,737', '00:25:22,974', '00:25:24,642', '00:25:26,878', '00:25:30,115', '00:25:32,784', '00:25:38,156', '00:25:46,164', '00:25:48,800', '00:25:50,802', '00:25:53,238', '00:25:55,107', '00:25:57,409', '00:25:59,078', '00:26:02,448', '00:26:06,352', '00:26:09,789', '00:26:13,560', '00:26:16,129', '00:26:17,433', '00:26:19,756', '00:26:21,301', '00:26:23,870', '00:26:26,739', '00:26:32,045', '00:26:34,047', '00:26:37,117', '00:26:40,687', '00:26:42,822', '00:26:45,158', '00:26:47,427', '00:26:49,596', '00:26:52,198', '00:26:54,467', '00:26:58,671', '00:27:00,607', '00:27:02,875', '00:27:05,511', '00:27:07,179', '00:27:09,981', '00:27:12,150', '00:27:14,252', '00:27:21,692', '00:27:24,228', '00:27:26,096', '00:27:28,532', '00:27:31,168', '00:27:33,070', '00:27:35,072', '00:27:37,241', '00:27:38,910', '00:27:40,745', '00:27:43,215', '00:27:44,783', '00:27:47,086', '00:27:50,356', '00:27:53,159', '00:28:00,366', '00:28:02,402', '00:28:05,071', '00:28:07,373', '00:28:09,409', '00:28:12,878', '00:28:15,747', '00:28:28,359', '00:28:30,428', '00:28:33,697', '00:28:36,000', '00:28:38,235', '00:28:40,270', '00:28:43,874', '00:28:46,210', '00:28:48,779', '00:28:51,015', '00:28:55,553', '00:28:57,589', '00:29:01,059', '00:29:03,930', '00:29:11,504', '00:29:13,239', '00:29:33,659', '00:30:07,290', '00:30:10,794', '00:30:16,098', '00:30:20,636', '00:30:22,838', '00:30:24,907', '00:30:27,076', '00:30:29,378', '00:30:31,715', '00:30:33,817', '00:30:37,021', '00:30:39,423', '00:30:44,763', '00:30:47,332', '00:30:50,635', '00:30:56,007', '00:30:58,210', '00:31:02,080', '00:31:04,116', '00:31:06,518', '00:31:09,388', '00:31:12,592', '00:31:16,463', '00:31:20,835', '00:31:28,208', '00:31:31,945', '00:31:39,017', '00:31:42,621', '00:31:45,257', '00:31:47,693', '00:31:49,862', '00:31:52,565', '00:31:56,203', '00:31:59,206', '00:32:02,276', '00:32:08,181', '00:32:13,753', '00:32:17,390', '00:32:23,963', '00:32:28,201', '00:32:30,770', '00:32:35,675', '00:32:41,714', '00:32:43,982', '00:32:45,417', '00:32:54,892', '00:32:58,128', '00:33:02,399', '00:33:05,702', '00:33:08,505', '00:33:12,909', '00:33:18,048', '00:33:20,518', '00:33:25,390', '00:33:27,025', '00:33:30,361', '00:33:35,232', '00:33:37,902', '00:33:40,504', '00:33:43,707', '00:33:46,643', '00:33:48,945', '00:33:53,216', '00:33:55,386', '00:33:57,988', '00:34:00,858', '00:34:03,828', '00:34:07,799', '00:34:09,901', '00:34:12,971', '00:34:17,610', '00:34:22,315', '00:34:29,287', '00:35:03,485', '00:35:05,954', '00:35:08,123', '00:35:10,458', '00:35:12,727', '00:35:15,696', '00:35:17,565', '00:35:19,299', '00:35:22,836', '00:35:26,307', '00:35:28,910', '00:35:32,480', '00:35:38,154', '00:35:40,957', '00:35:43,125', '00:35:45,494', '00:35:48,563', '00:35:50,966', '00:35:53,068', '00:36:05,213', '00:36:31,842', '00:36:33,978', '00:36:39,284', '00:36:43,021', '00:36:45,424', '00:36:50,629', '00:36:53,166', '00:36:56,002', '00:36:57,504', '00:36:59,540', '00:37:02,643', '00:37:10,317', '00:37:14,086', '00:37:16,989', '00:37:20,458', '00:37:26,865', '00:37:35,809', '00:37:39,714', '00:38:02,602', '00:38:04,970', '00:40:38,267', '00:40:50,779', '00:40:55,250', '00:40:57,519', '00:40:59,821', '00:41:03,191', '00:41:06,728', '00:41:09,264', '00:41:14,269', '00:41:16,071', '00:41:23,979', '00:41:25,880', '00:41:28,249', '00:41:34,356', '00:41:52,039', '00:41:55,276', '00:41:58,847', '00:42:01,383', '00:42:04,020', '00:42:07,556', '00:42:10,860', '00:42:15,264', '00:42:18,834', '00:42:25,173', '00:42:28,342', '00:42:30,577', '00:42:32,713', '00:42:34,548', '00:42:37,584', '00:42:40,620', '00:42:43,355', '00:42:46,925', '00:42:50,495', '00:42:53,065', '00:42:55,934', '00:42:58,103', '00:43:01,774', '00:43:04,544', '00:43:06,513', '00:43:08,081', '00:43:10,217', '00:43:12,186', '00:43:16,558', '00:43:20,061', '00:43:22,764', '00:43:25,633', '00:43:28,368', '00:43:31,938', '00:43:37,409', '00:43:43,148', '00:43:45,584', '00:43:46,890', '00:43:49,321', '00:43:51,523', '00:43:54,126', '00:43:56,195', '00:43:58,831', '00:44:00,766', '00:44:03,302', '00:44:06,571', '00:44:08,406', '00:44:10,809', '00:44:13,110', '00:44:15,480', '00:44:17,748', '00:44:21,251', '00:44:23,386', '00:44:26,289', '00:44:29,093', '00:44:31,729', '00:44:36,802', '00:44:39,004', '00:44:44,911', '00:44:48,447', '00:44:51,851', '00:45:02,695', '00:45:07,701', '00:45:11,205', '00:45:12,873', '00:45:15,043', '00:45:19,915', '00:45:23,119', '00:45:25,722', '00:45:29,559', '00:45:33,864', '00:45:38,936', '00:45:42,974', '00:45:51,215', '00:45:53,517', '00:45:55,351', '00:45:57,620', '00:45:59,588', '00:46:01,490', '00:46:05,027', '00:46:07,296', '00:46:12,334', '00:46:23,413', '00:46:26,316', '00:46:28,852', '00:46:32,356', '00:46:35,159', '00:46:36,995', '00:46:41,199', '00:46:43,335', '00:46:50,508', '00:46:53,777', '00:46:56,446', '00:46:58,614', '00:47:00,583', '00:47:21,805', '00:47:24,341', '00:47:26,843', '00:47:52,436', '00:47:58,175', '00:48:02,479', '00:48:05,683', '00:48:10,155', '00:48:15,461', '00:48:23,537', '00:48:29,142', '00:48:33,180', '00:48:35,548', '00:48:48,461', '00:48:50,396', '00:48:58,104', '00:49:00,973', '00:49:08,847', '00:49:11,850', '00:49:14,518', '00:49:17,087', '00:49:20,357', '00:49:23,426', '00:49:27,796', '00:49:30,265', '00:49:33,268', '00:49:36,103', '00:49:38,839', '00:49:41,942', '00:49:45,012', '00:49:49,283', '00:49:52,721', '00:49:56,158', '00:49:58,261', '00:50:00,196', '00:50:02,866', '00:50:04,935', '00:50:07,237', '00:50:09,472', '00:50:13,109', '00:50:16,678', '00:50:19,547', '00:50:22,683', '00:50:26,387', '00:50:29,056', '00:50:31,893', '00:50:34,796', '00:50:37,165', '00:51:47,338', '00:51:51,509', '00:51:53,478', '00:51:55,880', '00:51:58,884', '00:52:00,151', '00:52:02,220', '00:52:04,389', '00:52:06,558', '00:52:09,127', '00:52:11,195', '00:52:12,797', '00:52:15,400', '00:52:17,101', '00:52:19,371', '00:52:21,873', '00:52:35,619', '00:52:40,057', '00:52:42,592', '00:52:44,861', '00:52:47,363', '00:52:53,036', '00:52:54,571', '00:52:58,875', '00:53:01,211', '00:53:05,416', '00:53:09,588', '00:53:12,358', '00:53:13,926', '00:53:17,597', '00:53:19,766', '00:53:22,169', '00:53:24,638', '00:53:26,841', '00:53:29,210', '00:53:32,246', '00:53:34,348', '00:53:37,151', '00:53:40,954', '00:53:42,890', '00:53:45,258', '00:53:48,028', '00:53:52,299', '00:53:55,101', '00:53:56,903', '00:54:00,507', '00:54:03,443', '00:54:05,880', '00:54:08,082', '00:54:10,452', '00:54:13,121', '00:54:15,758', '00:54:18,628', '00:54:20,129', '00:54:23,132', '00:54:25,301', '00:54:27,737', '00:54:32,375', '00:54:34,376', '00:54:36,645', '00:54:40,382', '00:54:42,718', '00:54:44,486', '00:54:46,822', '00:54:51,759', '00:54:58,132', '00:55:11,646', '00:55:16,517', '00:55:28,862', '00:55:32,666', '00:55:34,267', '00:55:35,402', '00:55:37,037', '00:55:41,641', '00:55:43,676', '00:55:46,245', '00:55:48,147', '00:55:51,150', '00:55:58,190']

In [14]:
GOTep3=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Time_Start  800 non-null    object
 1   Time_End    800 non-null    object
 2   Text        800 non-null    object
dtypes: object(3)
memory usage: 18.9+ KB

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep3['Time_End'] = pd.to_datetime(GOTep3['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep3['Time_Start'] = pd.to_datetime(GOTep3['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep3['Time_End'] = pd.to_timedelta(GOTep3['Time_End'].astype(str))
GOTep3['Time_Start'] = pd.to_timedelta(GOTep3['Time_Start'].astype(str))

In [139]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep3['Time_Diff_seconds'] = GOTep3['Time_End'] - GOTep3['Time_Start']
GOTep3['Time_Diff_seconds'] = GOTep3['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep3.tail()

         Time_Start        Time_End              Text  Time_Diff_seconds
794 00:55:41.641000 00:55:43.642000      [Very dead.]              2.001
795 00:55:43.676000 00:55:46.211000           [Come.]              2.535
796 00:55:46.245000 00:55:48.113000       [Ah ah ah!]              1.868
797 00:55:48.147000 00:55:51.116000          [- Hup!]              2.969
798 00:55:51.150000 00:55:53.151000  [Again, faster.]              2.001

In [0]:
GOTep3.drop(index=799, inplace=True)

# episode 4

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp4.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep4=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep4.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep4['Time_End'] = pd.to_datetime(GOTep4['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep4['Time_Start'] = pd.to_datetime(GOTep4['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep4['Time_End'] = pd.to_timedelta(GOTep4['Time_End'].astype(str))
GOTep4['Time_Start'] = pd.to_timedelta(GOTep4['Time_Start'].astype(str))

In [22]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep4['Time_Diff_seconds'] = GOTep4['Time_End'] - GOTep4['Time_Start']
GOTep4['Time_Diff_seconds'] = GOTep4['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep4.head(50)

        Time_Start  ... Time_Diff_seconds
0  00:01:17.717000  ...             4.000
1  00:01:21.742000  ...             1.200
2  00:02:40.335000  ...             3.536
3  00:02:49.977000  ...             3.503
4  00:02:53.515000  ...             3.002
5  00:02:56.551000  ...             3.069
6  00:03:00.956000  ...             2.268
7  00:03:03.258000  ...             3.002
8  00:03:06.295000  ...             1.901
9  00:03:08.230000  ...             3.136
10 00:03:12.702000  ...             2.401
11 00:03:18.140000  ...             3.002
12 00:03:21.177000  ...             2.101
13 00:03:29.119000  ...             3.803
14 00:03:32.956000  ...             2.502
15 00:03:35.493000  ...             3.202
16 00:03:38.730000  ...             1.934
17 00:03:40.699000  ...             1.968
18 00:03:42.701000  ...             3.503
19 00:03:48.274000  ...             1.868
20 00:03:52.011000  ...             2.234
21 00:03:54.280000  ...             2.334
22 00:03:56.648000  ...             2.602
23 00:03:59.284000  ...             2.434
24 00:04:01.752000  ...             4.169
25 00:04:05.956000  ...             3.735
26 00:04:12.395000  ...             2.535
27 00:04:14.964000  ...             2.402
28 00:04:17.401000  ...             2.235
29 00:04:19.670000  ...             2.268
30 00:04:21.973000  ...             3.036
31 00:04:25.043000  ...             2.035
32 00:04:27.112000  ...             2.602
33 00:04:29.749000  ...             2.535
34 00:04:34.453000  ...             2.435
35 00:04:36.922000  ...             2.068
36 00:04:39.024000  ...             1.934
37 00:04:42.227000  ...             1.667
38 00:04:43.929000  ...             1.567
39 00:04:45.530000  ...             2.334
40 00:04:47.898000  ...             3.269
41 00:04:51.201000  ...             1.701
42 00:04:52.937000  ...             2.902
43 00:04:57.075000  ...             1.901
44 00:04:59.011000  ...             2.302
45 00:05:01.347000  ...             2.835
46 00:05:04.216000  ...             2.202
47 00:05:06.452000  ...             2.902
48 00:05:14.460000  ...             2.569
49 00:05:17.063000  ...             2.769

[50 rows x 4 columns]

#episode 5

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp5.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep5=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep5.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep5['Time_End'] = pd.to_datetime(GOTep5['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep5['Time_Start'] = pd.to_datetime(GOTep5['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep5['Time_End'] = pd.to_timedelta(GOTep5['Time_End'].astype(str))
GOTep5['Time_Start'] = pd.to_timedelta(GOTep5['Time_Start'].astype(str))

In [0]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep5['Time_Diff_seconds'] = GOTep5['Time_End'] - GOTep5['Time_Start']
GOTep5['Time_Diff_seconds'] = GOTep5['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep5.tail(5)

In [0]:
GOTep5.drop(index=850, inplace=True)

#episode 6

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp6.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep6=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep6.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep6['Time_End'] = pd.to_datetime(GOTep6['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep6['Time_Start'] = pd.to_datetime(GOTep6['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep6['Time_End'] = pd.to_timedelta(GOTep6['Time_End'].astype(str))
GOTep6['Time_Start'] = pd.to_timedelta(GOTep6['Time_Start'].astype(str))

In [145]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep6['Time_Diff_seconds'] = GOTep6['Time_End'] - GOTep6['Time_Start']
GOTep6['Time_Diff_seconds'] = GOTep6['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep6.tail()

         Time_Start  ... Time_Diff_seconds
647 00:50:58.768000  ...             2.935
648 00:51:03.306000  ...             2.502
649 00:51:20.791000  ...             2.368
650 00:51:23.193000  ...             2.202
651 00:51:26.564000  ...             2.636

[5 rows x 4 columns]

In [0]:
GOTep6.drop(index=652, inplace=True)

#episode 7

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp7.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep7=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep7.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep7['Time_End'] = pd.to_datetime(GOTep7['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep7['Time_Start'] = pd.to_datetime(GOTep7['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep7['Time_End'] = pd.to_timedelta(GOTep7['Time_End'].astype(str))
GOTep7['Time_Start'] = pd.to_timedelta(GOTep7['Time_Start'].astype(str))

In [150]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep7['Time_Diff_seconds'] = GOTep7['Time_End'] - GOTep7['Time_Start']
GOTep7['Time_Diff_seconds'] = GOTep7['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep7.tail()

         Time_Start  ... Time_Diff_seconds
689 00:57:38.318000  ...             1.432
690 00:57:44.248000  ...             1.752
691 00:57:46.758000  ...             4.232
692 00:57:53.288000  ...             1.092
693 00:58:05.817000  ...             2.893

[5 rows x 4 columns]

In [0]:
GOTep7.drop(index=694, inplace=True)

In [0]:
GOTep7.drop(index=695, inplace=True)

#episode 8

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp8.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep8=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep8.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep8['Time_End'] = pd.to_datetime(GOTep8['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep8['Time_Start'] = pd.to_datetime(GOTep8['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep8['Time_End'] = pd.to_timedelta(GOTep8['Time_End'].astype(str))
GOTep8['Time_Start'] = pd.to_timedelta(GOTep8['Time_Start'].astype(str))

In [153]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep8['Time_Diff_seconds'] = GOTep8['Time_End'] - GOTep8['Time_Start']
GOTep8['Time_Diff_seconds'] = GOTep8['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep8.tail()

         Time_Start  ... Time_Diff_seconds
685 00:56:30.764000  ...             2.267
686 00:56:35.435000  ...             2.567
687 00:56:38.037000  ...             3.602
688 00:56:44.542000  ...             2.135
689 00:56:51.149000  ...             2.101

[5 rows x 4 columns]

In [0]:
GOTep8.drop(index=690,inplace=True)

#episode 9

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp9.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep9=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep9.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep9['Time_End'] = pd.to_datetime(GOTep9['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep9['Time_Start'] = pd.to_datetime(GOTep9['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep9['Time_End'] = pd.to_timedelta(GOTep9['Time_End'].astype(str))
GOTep9['Time_Start'] = pd.to_timedelta(GOTep9['Time_Start'].astype(str))

In [156]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep9['Time_Diff_seconds'] = GOTep9['Time_End'] - GOTep9['Time_Start']
GOTep9['Time_Diff_seconds'] = GOTep9['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep9.tail()

         Time_Start  ... Time_Diff_seconds
720 00:54:13.618000  ...             2.968
721 00:54:16.620000  ...             2.769
722 00:54:19.423000  ...             2.068
723 00:54:21.525000  ...             1.534
724 00:54:26.530000  ...             1.933

[5 rows x 4 columns]

In [0]:
GOTep9.drop(index=725,inplace=True)

#episode 10

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp10.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep10=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep10.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep10['Time_End'] = pd.to_datetime(GOTep10['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep10['Time_Start'] = pd.to_datetime(GOTep10['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep10['Time_End'] = pd.to_timedelta(GOTep10['Time_End'].astype(str))
GOTep10['Time_Start'] = pd.to_timedelta(GOTep10['Time_Start'].astype(str))

In [159]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep10['Time_Diff_seconds'] = GOTep10['Time_End'] - GOTep10['Time_Start']
GOTep10['Time_Diff_seconds'] = GOTep10['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep10.tail(5)

         Time_Start  ... Time_Diff_seconds
638 00:47:57.214000  ...             1.868
639 00:47:59.116000  ...             2.034
640 00:48:03.121000  ...             2.534
641 00:48:05.690000  ...             2.502
642 00:50:38.409000  ...             2.869

[5 rows x 4 columns]

In [0]:
GOTep10.drop(index=643,inplace=True)

# Season 2 Episode 1

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp1S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep1S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep1S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep1S2['Time_End'] = pd.to_datetime(GOTep1S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep1S2['Time_Start'] = pd.to_datetime(GOTep1S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep1S2['Time_End'] = pd.to_timedelta(GOTep1S2['Time_End'].astype(str))
GOTep1S2['Time_Start'] = pd.to_timedelta(GOTep1S2['Time_Start'].astype(str))

In [0]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep1S2['Time_Diff_seconds'] = GOTep1S2['Time_End'] - GOTep1S2['Time_Start']
GOTep1S2['Time_Diff_seconds'] = GOTep1S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep1S2.tail()

In [0]:
GOTep1S2.drop(index=806,inplace=True)

#Episode 2 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp2S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep2S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep2S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep2S2['Time_End'] = pd.to_datetime(GOTep2S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep2S2['Time_Start'] = pd.to_datetime(GOTep2S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep2S2['Time_End'] = pd.to_timedelta(GOTep2S2['Time_End'].astype(str))
GOTep2S2['Time_Start'] = pd.to_timedelta(GOTep2S2['Time_Start'].astype(str))

In [165]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep2S2['Time_Diff_seconds'] = GOTep2S2['Time_End'] - GOTep2S2['Time_Start']
GOTep2S2['Time_Diff_seconds'] = GOTep2S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep2S2.tail()

         Time_Start  ... Time_Diff_seconds
809 00:50:32.640000  ...             3.035
810 00:50:35.743000  ...             4.704
811 00:50:40.481000  ...             2.168
812 00:50:48.622000  ...             4.470
813 00:50:55.429000  ...             2.101

[5 rows x 4 columns]

In [0]:
GOTep2S2.drop(index=814,inplace=True)
GOTep2S2.drop(index=815,inplace=True)

# Episode 3 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp3S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep3S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep3S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep3S2['Time_End'] = pd.to_datetime(GOTep3S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep3S2['Time_Start'] = pd.to_datetime(GOTep3S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep3S2['Time_End'] = pd.to_timedelta(GOTep3S2['Time_End'].astype(str))
GOTep3S2['Time_Start'] = pd.to_timedelta(GOTep3S2['Time_Start'].astype(str))

In [168]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep3S2['Time_Diff_seconds'] = GOTep3S2['Time_End'] - GOTep3S2['Time_Start']
GOTep3S2['Time_Diff_seconds'] = GOTep3S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep3S2.tail()

         Time_Start  ... Time_Diff_seconds
777 00:52:15.712000  ...             2.268
778 00:52:30.394000  ...             1.667
779 00:52:35.499000  ...             2.301
780 00:52:41.971000  ...             2.502
781 00:52:55.216000  ...             3.702

[5 rows x 4 columns]

In [0]:
GOTep3S2.drop(index=782,inplace=True)

# Episode 4 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp4S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep4S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep4S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep4S2['Time_End'] = pd.to_datetime(GOTep4S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep4S2['Time_Start'] = pd.to_datetime(GOTep4S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep4S2['Time_End'] = pd.to_timedelta(GOTep4S2['Time_End'].astype(str))
GOTep4S2['Time_Start'] = pd.to_timedelta(GOTep4S2['Time_Start'].astype(str))

In [171]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep4S2['Time_Diff_seconds'] = GOTep4S2['Time_End'] - GOTep4S2['Time_Start']
GOTep4S2['Time_Diff_seconds'] = GOTep4S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep4S2.tail()

         Time_Start        Time_End             Text  Time_Diff_seconds
792 00:50:16.523000 00:50:18.290000      [( Moans )]              1.767
793 00:50:38.178000 00:50:41.181000  [( Screaming )]              3.003
794 00:50:45.754000 00:50:48.557000  [( Shrieking )]              2.803
795 00:50:52.795000 00:50:54.796000  [( Shrieking )]              2.001
796 00:51:09.145000 00:51:11.614000     [( Growls )]              2.469

In [0]:
GOTep4S2.drop(index=797,inplace=True)
GOTep4S2.drop(index=798,inplace=True)

# Episode 5 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp5S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep5S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep5S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep5S2['Time_End'] = pd.to_datetime(GOTep5S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep5S2['Time_Start'] = pd.to_datetime(GOTep5S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep5S2['Time_End'] = pd.to_timedelta(GOTep5S2['Time_End'].astype(str))
GOTep5S2['Time_Start'] = pd.to_timedelta(GOTep5S2['Time_Start'].astype(str))

In [174]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep5S2['Time_Diff_seconds'] = GOTep5S2['Time_End'] - GOTep5S2['Time_Start']
GOTep5S2['Time_Diff_seconds'] = GOTep5S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep5S2.tail()

         Time_Start  ... Time_Diff_seconds
878 00:53:52.903000  ...             3.802
879 00:54:00.442000  ...             1.968
880 00:54:02.444000  ...             2.201
881 00:54:11.252000  ...             2.000
882 00:54:14.888000  ...             3.470

[5 rows x 4 columns]

In [0]:
GOTep5S2.drop(index=883,inplace=True)

# Episode 6 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp6S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep6S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep6S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep6S2['Time_End'] = pd.to_datetime(GOTep6S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep6S2['Time_Start'] = pd.to_datetime(GOTep6S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep6S2['Time_End'] = pd.to_timedelta(GOTep6S2['Time_End'].astype(str))
GOTep6S2['Time_Start'] = pd.to_timedelta(GOTep6S2['Time_Start'].astype(str))

In [180]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep6S2['Time_Diff_seconds'] = GOTep6S2['Time_End'] - GOTep6S2['Time_Start']
GOTep6S2['Time_Diff_seconds'] = GOTep6S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep6S2.tail()

         Time_Start  ... Time_Diff_seconds
724 00:51:24.373000  ...             4.003
725 00:51:29.670000  ...             3.086
726 00:51:45.895000  ...             2.960
727 00:51:49.982000  ...             1.292
728 00:52:01.702000  ...             1.334

[5 rows x 4 columns]

In [0]:
GOTep6S2.drop(index=729,inplace=True)

# Episode 7 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp7S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep7S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep7S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep7S2['Time_End'] = pd.to_datetime(GOTep7S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep7S2['Time_Start'] = pd.to_datetime(GOTep7S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep7S2['Time_End'] = pd.to_timedelta(GOTep7S2['Time_End'].astype(str))
GOTep7S2['Time_Start'] = pd.to_timedelta(GOTep7S2['Time_Start'].astype(str))

In [183]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep7S2['Time_Diff_seconds'] = GOTep7S2['Time_End'] - GOTep7S2['Time_Start']
GOTep7S2['Time_Diff_seconds'] = GOTep7S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep7S2.tail()

         Time_Start  ... Time_Diff_seconds
756 00:53:10.896000  ...             3.002
757 00:53:15.609000  ...             1.918
758 00:53:17.945000  ...             2.710
759 00:53:20.739000  ...             3.837
760 00:53:27.621000  ...             1.834

[5 rows x 4 columns]

In [0]:
GOTep7S2.drop(index=761,inplace=True)

# Episode 8 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp8S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep8S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep8S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep8S2['Time_End'] = pd.to_datetime(GOTep8S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep8S2['Time_Start'] = pd.to_datetime(GOTep8S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep8S2['Time_End'] = pd.to_timedelta(GOTep8S2['Time_End'].astype(str))
GOTep8S2['Time_Start'] = pd.to_timedelta(GOTep8S2['Time_Start'].astype(str))

In [184]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep8S2['Time_Diff_seconds'] = GOTep8S2['Time_End'] - GOTep8S2['Time_Start']
GOTep8S2['Time_Diff_seconds'] = GOTep8S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep8S2.tail()

         Time_Start  ... Time_Diff_seconds
769 00:51:38.679000  ...             2.752
770 00:51:42.850000  ...             1.667
771 00:51:45.853000  ...             2.501
772 00:51:48.439000  ...             1.876
773 00:51:51.984000  ...             2.585

[5 rows x 4 columns]

# Episode 9 S2

In [0]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp9S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

In [0]:
GOTep9S2=pd.DataFrame(list(zip(Time_starts,Time_ends,lines)),columns=['Time_Start','Time_End', 'Text'])
GOTep9S2.info()

In [0]:
# Changing datetime format so it can be converted to a timedelta64 as a string (was getting error converting to timedelta without this step)
GOTep9S2['Time_End'] = pd.to_datetime(GOTep9S2['Time_End'],format= '%H:%M:%S,%f' ).dt.time
GOTep9S2['Time_Start'] = pd.to_datetime(GOTep9S2['Time_Start'],format= '%H:%M:%S,%f' ).dt.time

In [0]:
# Converting the timeseries to a time delta in order to find the differences between time_end and time_start
GOTep9S2['Time_End'] = pd.to_timedelta(GOTep9S2['Time_End'].astype(str))
GOTep9S2['Time_Start'] = pd.to_timedelta(GOTep9S2['Time_Start'].astype(str))

In [185]:
# Creating a new column with differnce between time end and time start for each subtitle (length of time of each subtitle)
GOTep9S2['Time_Diff_seconds'] = GOTep9S2['Time_End'] - GOTep9S2['Time_Start']
GOTep9S2['Time_Diff_seconds'] = GOTep9S2['Time_Diff_seconds']/np.timedelta64(1,'s')

GOTep9S2.tail()

         Time_Start  ... Time_Diff_seconds
720 00:55:28.622000  ...             4.970
721 00:55:33.627000  ...             5.038
722 00:55:38.699000  ...             4.638
723 00:55:43.371000  ...             5.239
724 00:55:48.644000  ...             5.372

[5 rows x 4 columns]

# Episode 10 S2

In [127]:
#Read the subtitle file line-by-line extract using re
import urllib.request
file=urllib.request.urlopen('https://raw.githubusercontent.com/trong-shen/Game-of-Throne-Project/master/GOTsubtitles/subtitlesEp10S2.srt')
sub=[]
for line in file:
  decoded_line=line.decode("utf-8")
  sub.append(decoded_line)
re_pattern = r'[0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3}'
regex = re.compile(re_pattern)
start_times = list(filter(regex.search, sub))
Time_starts= [time.split(' ')[0] for time in start_times]
Time_ends=[time.split(' ')[2][0:-2] for time in start_times]
print(Time_starts)
print(Time_ends)

# Get lines
lines =[[]]
for sentence in sub:
    if re.match(re_pattern, sentence):
        lines[-1].pop()
        lines.append([])
    else:
        sentence_remove=sentence.replace("<i>","")
        sentence_remove=sentence_remove.replace("</i>","")
        sentence_remove=sentence_remove.replace("\r\n","")
        if not(sentence_remove==''):
          lines[-1].append(sentence_remove)
lines = lines[1:]

UnicodeDecodeError: ignored